### ISSUE TITLE
サイボウズの赤字の取り扱い方

### ISSUE THREAD

**Issue by ghost** [huggys/yasuhiro#3]
約5年分の_サイボウズの赤字_を保持している。

Publicで公開すると情報漏洩となりうるため、Privateで公開したい。

例えば
- 環境変数でもつ
- APIを別途用意する

**Comment by ghost** [comment]
Base64エンコード → 環境変数
とかできますかね

**Comment by rryyooggoo** [comment]
Base64エンコード → 環境変数
思いつかなかったです
確かにできますねエンコードデコードで

**Comment by ghost** [comment]
専用のAPIを作ることに決定
